# Generated by Django 5.0.6 on 2026-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
    ]
